services:
  - type: web
    name: losblancosfc
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDIA_STORAGE
        value: cloudinary
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: true
      - key: SESSION_SECRET
        sync: false
      - key: OWNER_EMAIL
        sync: false
      - key: OWNER_PASSWORD
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: CLOUDINARY_URL
        sync: false
